### ISSUE TITLE
Oracle JDK

### ISSUE THREAD

**Issue by pmorton** [rcarmo/docker-templates#7]
Hey - I noticed you are using the Oracle JDK you should consider switching to OpenJDK if you are distributing this container in a public registry.

http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

**Comment by rcarmo** [comment]
That article is interesting, because it was edited a few times since I saw it in March and still reads a lot like click bait. I wish I could find a counter-piece that was on HN the following day and which pointed out a number of fallacies in it, but it's 1AM here and my Google-fu is failing me now.

But I remember the gist of it, which is that Oracle's license agreement stipulates that their software should not be modified (which it isn't, thanks to the webupd8 team's installer, which even retains a full cached copy of the installation archive) and that it includes a copy of their license (which again it does). Since I'm not shaving off bits to decrease the image size (a key scary no-no in the article), that removes the matter of alteration and leaves the issue of redistribution per se and re-use by users.

Re-reading sections C and H of their license, the only relevant bit would seem to be the requirement to state that commercial use warrants licensing, but even then that only pertains to the "commercial features" listed in a separate table - which actually doesn't refer to the JDK proper.

Since neither of us are lawyers (I think), I'll gladly leave this issue open until a better conclusion is reached, or until it becomes moot by my updating the image (OpenJDK is something I usually avoid for performance and edge case compatibility issues).

**Comment by rcarmo** [comment]
I'm closing this due to moving that template to its own standalone repository - feel free to re-open the issue [there](https://github.com/rcarmo/azure-toolbox) if you still feel it's warranted.
